Feat/shaddollxz/ts config
Byzanteam/jet-linter pull request #21
Opened 2023-01-31 09:42 UTC by shaddollxz

2023-01-31 10:45 UTC, moonRider requested changes

2023-01-31 10:45 UTC, moonRider commented on packages/tsconfig/package.json
> +  "exports": {
files 也写一下。另外把 usage 更新一下，怎么使用的

2023-01-31 11:36 UTC, moonRider requested changes
这几个规则加一下
```json
{
  "exactOptionalPropertyTypes": true,
  "noFallthroughCasesInSwitch": true,
  "target": "ES6",
  "module": "esnext",
  "moduleResolution": "nodenext",
  "resolveJsonModule": true,
  "skipLibCheck": true
}
```

2023-01-31 11:36 UTC, moonRider commented on packages/tsconfig/tsconfig.base.json
> +    "allowJs": true,
这个关掉，不要 js 支持

2023-01-31 11:36 UTC, moonRider commented on packages/tsconfig/tsconfig.base.json
>      "noUnusedParameters": false,
这两个不要了，eslint 去检查这两个。

2023-02-01 03:45 UTC, moonRider requested changes

2023-02-01 03:45 UTC, moonRider commented on README.md
> +**[how to use](https://github.com/Byzanteam/jet-linter/blob/main/packages/tsconfig/README.md)**
改用相对路径哈

2023-02-01 06:22 UTC, moonRider approved these changes

2023-02-01 06:22 UTC, moonRider commented on README.md
> +**[how to use](/Byzanteam/jet-linter/blob/main/packages/tsconfig/README.md)**
```suggestion
**[how to use](/packages/tsconfig/README.md)**
```

2023-02-01 06:30 UTC, shaddollxz commented on README.md
> +**[how to use](/Byzanteam/jet-linter/blob/main/packages/tsconfig/README.md)**
> 

它的根是 https://github.com 相对路径用这个会走404的

2023-02-01 06:31 UTC, moonRider commented on README.md
> +**[how to use](/Byzanteam/jet-linter/blob/main/packages/tsconfig/README.md)**
https://github.com/Byzanteam/jet-actions
按这个来

2023-02-01 06:37 UTC, moonRider commented on README.md
> +**[how to use](/packages/tsconfig/README.md)**
不需要到 README.md，到目录就好了

2023-02-01 06:42 UTC, moonRider submitted a review, later dismissed

2023-02-01 06:44 UTC, moonRider approved these changes

2023-02-01 06:47 UTC, merged