Fix/shaddollxz/eslint
Byzanteam/jet-linter pull request #27
Opened 2023-02-01 08:26 UTC by shaddollxz

2023-02-01 08:37 UTC, moonRider requested changes

2023-02-01 08:49 UTC, shaddollxz commented on .changeset/olive-icons-know.md
> +add @rushstack/eslint-patch to eslint-config peerDependencies, fix eslint-config-vue-ts extends order
如果直接 extends 现在的配置，eslint 会在当前项目下的 node_modules 里找配置中 extends 的配置，用这个包解决这个问题

参考这个 https://github.com/vuejs/eslint-config-prettier#installation

2023-02-01 09:06 UTC, moonRider commented on .changeset/olive-icons-know.md
> +add @rushstack/eslint-patch to eslint-config peerDependencies, fix eslint-config-vue-ts extends order
要不不用extends vue/tsconfig.json 了，把需要的直接在这里写吧。感觉用到的也不多，单独用一个依赖有点大材小用了？

2023-02-01 09:09 UTC, shaddollxz commented on .changeset/olive-icons-know.md
> +add @rushstack/eslint-patch to eslint-config peerDependencies, fix eslint-config-vue-ts extends order
好，正好和 eslint-ts 中的配置做个去重

2023-02-02 03:15 UTC, moonRider approved these changes

2023-02-02 03:33 UTC, merged