dfeat: use prettier sort import
Byzanteam/jet-linter pull request #70
Opened 2024-03-15 09:44 UTC by shaddollxz

2024-03-15 10:00 UTC, moonRider requested changes

2024-03-15 10:00 UTC, moonRider commented on packages/prettier/package.json
> +    "@vue/compiler-sfc": "^3.4.21",
为啥会有这个依赖呀？

2024-03-17 09:17 UTC, shaddollxz commented on packages/prettier/package.json
> +    "@vue/compiler-sfc": "^3.4.21",
这个插件在 vue 中使用必须得带上这个依赖，试了下在实际使用的项目里安装没用，只能在这里装
[The Stanley Parable: Ultra Deluxe](https://store.steampowered.com/app/1703340/?snr=1_wishlist_4__wishlist-capsule)

2024-03-18 02:12 UTC, moonRider commented on packages/prettier/package.json
> +    "@vue/compiler-sfc": "^3.4.21",
我看了下，是要求 peerDependencies

2024-03-18 03:53 UTC, shaddollxz commented on packages/prettier/package.json
> +    "@vue/compiler-sfc": "^3.4.21",
但我们的这个 prettier 是为 vue react node 三种项目提供格式化支持，为了保证能为 vue 提供格式化，只能在这里多带一个依赖（在使用这个配置的项目里安装它这个插件是读取不到 sfc 里的东西的）
如果单独为 vue 整一个 prettier 配置，会出现两个包一模一样，只有依赖不一样的奇怪情况，这样不咋好

2024-03-18 04:46 UTC, moonRider approved these changes

2024-03-18 06:05 UTC, merged